default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0
  
development:
  <<: *default
  database: mepibo_development

test:
  <<: *default
  database: mepibo_test

production:
  <<: *default
  database: mepibo_production
  username: mepibo
  password: <%= ENV['MEPIBO_DATABASE_PASSWORD'] %>