# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6deefec428ba12ecf3bba6006df375e587f04ecaef30b67065faf9b677e9fe365f1943ac205fe50a28b84035de1b70f6e8d6866d11744cf3862e118d00e4d2f6

test:
  secret_key_base: 46694f81274025fab8fb095872667a766af652581436798023738a3f62136d7b8e5cf988b307b208b51e1d139a7f648af7f47686f636ccf2c48c1bf9be21eeaa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
